### ISSUE TITLE
DB entry does not save values

### ISSUE THREAD

**Issue by jeffklawiter** [wkallhof/activity-tracker#1]
Inserted values use nameof instead of the actual value. 

https://github.com/wkallhof/activity-tracker/blob/920354b78fb3b88e8518dcf6a3d61cbbf13de2f8/ActivityTracker.Core/Features/Screenshots/ScreenshotService.cs#L51-L60

**Comment by wkallhof** [comment]
Jeff! Thanks for the second pair of eyes, I wasn't expecting any input this early :) 

I'm not entirely sold on this pattern of using "nameof" to avoid hard coding the SQL statement columns and values, but it just felt  _wrong_ to see all of those property names hard coded in a string. I'm sure this will bite me at some point.

In this case, I'm using Dapper, which allows you to parameterize the sql statements with the property names of a passed in object to fill in values. Note the very easy to miss "@" characters before the interpolation string value entry for the `VALUES` section. 

```
VALUES(@{nameof(Screenshot.ActivityLogEntryId)},  
                     @{nameof(Screenshot.CreateDate)}, 
                     @{nameof(Screenshot.Data)}); 
```
will result in 
```
VALUES(@ActivityLogEntryId,  
                     @CreateDate, 
                     @Data); 
```
Which is accurate in this case. Dapper will replace the `@CreateDate` part of the query with the `CreateDate` property value of the object I pass in, which is a `Screenshot`. 

The fact that it takes this much time to explain and that you had a problem seeing the formatting means this probably isn't a great solution... 

Thanks again! Feel free to call out any other bullshit you see.

**Comment by jeffklawiter** [comment]
ahhh.. magic strings :).  Ya know now thinking about I remember having to do it like this on the only project I ever used Dapper on. But that was quite a while ago. 

Is this DB meant to be shared between the console app and the website? Curious if an Object DB like LiteDB may be a better option. 

I raised this issue as more of a way saying hey ;)
